"""
Deal Radar OS — Northern Virginia Seed Data
=============================================
15 realistic NoVA small-to-mid office properties across all 5 submarkets.
8 realistic companies with tenant-side signals.

Signal scores are computed automatically by the pipeline after seeding.
Pre-seeded properties are designed to produce diverse output:
  - High pre-market predictions (long-held, high vacancy)
  - Active mispriced listings (below-market rents + high DOM)
  - Tenant matches (companies matched to nearby vacancy)
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from datetime import date, datetime
from app.database import init_db, SessionLocal
from app.models.property import Property
from app.models.company import Company
from app.ingestion.pipeline import run_full_pipeline

CURRENT_YEAR = 2026


def seed_properties(db):
    properties = [
        # ── RESTON ─────────────────────────────────────────────────────────
        Property(
            property_id="NVA-001",
            address="1760 Reston Pkwy, Suite 200, Reston, VA 20190",
            submarket="Reston",
            asset_class="Class B",
            total_sf=22_000,
            year_built=2000,
            last_renovation_year=2011,
            num_floors=4,
            owner_name="1760 Reston LLC",
            owner_type="LLC",
            owner_phone="703-555-0101",
            owner_email="jharris@1760reston.com",
            acquisition_date=date(2012, 6, 15),
            acquisition_price=3_900_000,
            in_place_rent_psf=24.50,
            market_rent_psf=28.50,
            market_cap_rate=6.5,
            cap_rate=5.8,
            noi=222_200,
            occupancy_pct=62.0,
            vacancy_pct=38.0,
            vacancy_12mo_ago=28.0,
            leased_sf=13_640,
            vacant_sf=8_360,
            sf_expiring_12mo=6_600,
            sf_expiring_24mo=9_900,
            lease_rollover_pct=30.0,
            last_lease_signed_date=date(2022, 3, 10),
            years_since_last_lease=4.0,
            is_listed=False,
            estimated_loan_maturity_year=2027,
            estimated_ltv=0.65,
            notes="Private LLC owner, unresponsive to brokers historically. Vacancy spiking."
        ),
        Property(
            property_id="NVA-002",
            address="10600 Sunset Hills Rd, Suite 100, Reston, VA 20190",
            submarket="Reston",
            asset_class="Class B",
            total_sf=28_000,
            year_built=2003,
            last_renovation_year=None,
            num_floors=5,
            owner_name="Sunset Hills Office LLC",
            owner_type="LLC",
            owner_phone="703-555-0102",
            acquisition_date=date(2014, 9, 22),
            acquisition_price=6_800_000,
            in_place_rent_psf=26.00,
            market_rent_psf=28.50,
            market_cap_rate=6.5,
            cap_rate=5.9,
            noi=368_200,
            occupancy_pct=60.0,
            vacancy_pct=40.0,
            vacancy_12mo_ago=32.0,
            leased_sf=16_800,
            vacant_sf=11_200,
            sf_expiring_12mo=10_080,
            sf_expiring_24mo=14_000,
            lease_rollover_pct=36.0,
            last_lease_signed_date=date(2021, 11, 5),
            years_since_last_lease=4.5,
            is_listed=False,
            estimated_loan_maturity_year=2026,
            estimated_ltv=0.70,
            notes="Loan maturity this year. Owner likely facing refinance or sale decision."
        ),
        Property(
            property_id="NVA-003",
            address="1875 Explorer St, Suite 400, Reston Town Center, VA 20190",
            submarket="Reston",
            asset_class="Class A",
            total_sf=25_000,
            year_built=2006,
            last_renovation_year=2018,
            num_floors=6,
            owner_name="North Point Realty Group",
            owner_type="LLC",
            owner_phone="703-555-0103",
            acquisition_date=date(2013, 4, 1),
            acquisition_price=5_900_000,
            in_place_rent_psf=28.00,
            market_rent_psf=29.00,
            market_cap_rate=6.5,
            cap_rate=6.5,
            noi=392_000,
            occupancy_pct=82.0,
            vacancy_pct=18.0,
            vacancy_12mo_ago=20.0,
            leased_sf=20_500,
            vacant_sf=4_500,
            sf_expiring_12mo=5_000,
            sf_expiring_24mo=8_750,
            lease_rollover_pct=20.0,
            last_lease_signed_date=date(2024, 1, 15),
            years_since_last_lease=2.0,
            is_listed=False,
            notes="Well-managed but 13yr hold. Strong Reston Town Center asset — approaching exit window."
        ),
        # ── TYSONS ─────────────────────────────────────────────────────────
        Property(
            property_id="NVA-004",
            address="8300 Boone Blvd, Suite 200, Vienna, VA 22182",
            submarket="Tysons",
            asset_class="Class B",
            total_sf=25_000,
            year_built=2008,
            last_renovation_year=None,
            num_floors=5,
            owner_name="Boone Capital Group LLC",
            owner_type="LLC",
            owner_phone="703-555-0104",
            owner_email="mgomez@boonecapital.com",
            acquisition_date=date(2016, 2, 14),
            acquisition_price=4_100_000,
            in_place_rent_psf=19.00,
            market_rent_psf=27.00,
            market_cap_rate=6.2,
            cap_rate=4.2,
            noi=229_100,
            occupancy_pct=38.0,
            vacancy_pct=62.0,
            vacancy_12mo_ago=40.0,
            leased_sf=9_500,
            vacant_sf=15_500,
            sf_expiring_12mo=7_125,
            sf_expiring_24mo=9_500,
            lease_rollover_pct=28.5,
            last_lease_signed_date=date(2021, 6, 1),
            years_since_last_lease=5.0,
            is_listed=False,
            estimated_loan_maturity_year=2026,
            estimated_ltv=0.72,
            notes="HIGHEST SIGNAL. 62% vacant, loan maturing 2026, in-place rents 30% below mkt. 10yr hold."
        ),
        Property(
            property_id="NVA-005",
            address="7900 Westpark Dr, Suite 300, McLean, VA 22102",
            submarket="Tysons",
            asset_class="Class B",
            total_sf=24_500,
            year_built=1998,
            last_renovation_year=2008,
            num_floors=6,
            owner_name="Westpark Office Trust",
            owner_type="REIT/FUND",
            owner_phone="703-555-0105",
            acquisition_date=date(2009, 7, 18),
            acquisition_price=5_200_000,
            in_place_rent_psf=20.00,
            market_rent_psf=26.50,
            market_cap_rate=6.2,
            cap_rate=4.5,
            noi=294_000,
            occupancy_pct=42.0,
            vacancy_pct=58.0,
            vacancy_12mo_ago=50.0,
            leased_sf=10_290,
            vacant_sf=14_210,
            sf_expiring_12mo=6_174,
            sf_expiring_24mo=10_290,
            lease_rollover_pct=25.2,
            last_lease_signed_date=date(2020, 8, 15),
            years_since_last_lease=5.5,
            is_listed=True,
            listing_date=date(2025, 9, 15),
            days_on_market=208,
            submarket_avg_dom=130,
            asking_price=5_800_000,
            asking_price_psf=236.73,
            notes="Listed 208 days. 1.6x submarket avg DOM. Owner fatigued after 17yr hold."
        ),
        Property(
            property_id="NVA-006",
            address="8000 Towers Crescent Dr, Suite 100, Vienna, VA 22182",
            submarket="Tysons",
            asset_class="Class B",
            total_sf=19_800,
            year_built=2004,
            last_renovation_year=2015,
            num_floors=4,
            owner_name="Towers Crescent Partners",
            owner_type="LP",
            owner_phone="703-555-0106",
            acquisition_date=date(2015, 3, 25),
            acquisition_price=4_800_000,
            in_place_rent_psf=21.00,
            market_rent_psf=27.00,
            market_cap_rate=6.2,
            cap_rate=4.9,
            noi=237_600,
            occupancy_pct=45.0,
            vacancy_pct=55.0,
            vacancy_12mo_ago=38.0,
            leased_sf=8_910,
            vacant_sf=10_890,
            sf_expiring_12mo=5_346,
            sf_expiring_24mo=8_019,
            lease_rollover_pct=27.0,
            last_lease_signed_date=date(2022, 2, 28),
            years_since_last_lease=4.1,
            is_listed=False,
            estimated_loan_maturity_year=2027,
            notes="LP structure — investor pressure building as 11yr hold approaches."
        ),
        # ── ARLINGTON ──────────────────────────────────────────────────────
        Property(
            property_id="NVA-007",
            address="3100 Clarendon Blvd, Suite 300, Arlington, VA 22201",
            submarket="Arlington (Clarendon)",
            asset_class="Class B",
            total_sf=14_500,
            year_built=1997,
            last_renovation_year=None,
            num_floors=4,
            owner_name="Meridian Office Partners LLC",
            owner_type="LLC",
            owner_phone="703-555-0107",
            owner_email="schen@meridianpartners.com",
            acquisition_date=date(2010, 5, 12),
            acquisition_price=3_500_000,
            in_place_rent_psf=26.00,
            market_rent_psf=33.00,
            market_cap_rate=6.0,
            cap_rate=5.2,
            noi=199_680,
            occupancy_pct=58.0,
            vacancy_pct=42.0,
            vacancy_12mo_ago=30.0,
            leased_sf=8_410,
            vacant_sf=6_090,
            sf_expiring_12mo=5_075,
            sf_expiring_24mo=7_613,
            lease_rollover_pct=35.0,
            last_lease_signed_date=date(2023, 1, 20),
            years_since_last_lease=3.0,
            is_listed=True,
            listing_date=date(2025, 11, 1),
            days_on_market=161,
            submarket_avg_dom=95,
            asking_price=3_800_000,
            asking_price_psf=262.07,
            notes="Listed at compressed cap vs mkt. 16yr hold, 29yr old building, no renovation."
        ),
        Property(
            property_id="NVA-008",
            address="1800 N Kent St, Suite 600, Arlington, VA 22209",
            submarket="Arlington (Rosslyn)",
            asset_class="Class B",
            total_sf=17_600,
            year_built=2001,
            last_renovation_year=2012,
            num_floors=6,
            owner_name="Rosslyn Gateway LLC",
            owner_type="LLC",
            owner_phone="703-555-0108",
            acquisition_date=date(2011, 8, 30),
            acquisition_price=4_400_000,
            in_place_rent_psf=28.00,
            market_rent_psf=34.00,
            market_cap_rate=5.9,
            cap_rate=5.1,
            noi=248_600,
            occupancy_pct=52.0,
            vacancy_pct=48.0,
            vacancy_12mo_ago=38.0,
            leased_sf=9_152,
            vacant_sf=8_448,
            sf_expiring_12mo=4_576,
            sf_expiring_24mo=7_322,
            lease_rollover_pct=26.0,
            last_lease_signed_date=date(2022, 9, 1),
            years_since_last_lease=3.6,
            is_listed=False,
            estimated_loan_maturity_year=2028,
            notes="Rosslyn premium market. Owner unresponsive to leasing agents."
        ),
        Property(
            property_id="NVA-009",
            address="901 N Stuart St, Suite 200, Arlington, VA 22203",
            submarket="Arlington (Ballston)",
            asset_class="Class A",
            total_sf=16_200,
            year_built=2005,
            last_renovation_year=2019,
            num_floors=5,
            owner_name="Stuart Street Capital",
            owner_type="LLC",
            owner_phone="703-555-0109",
            acquisition_date=date(2015, 11, 5),
            acquisition_price=3_800_000,
            in_place_rent_psf=32.00,
            market_rent_psf=34.00,
            market_cap_rate=6.2,
            cap_rate=6.8,
            noi=327_600,
            occupancy_pct=78.0,
            vacancy_pct=22.0,
            vacancy_12mo_ago=25.0,
            leased_sf=12_636,
            vacant_sf=3_564,
            sf_expiring_12mo=3_240,
            sf_expiring_24mo=6_480,
            lease_rollover_pct=20.0,
            last_lease_signed_date=date(2024, 4, 10),
            years_since_last_lease=1.8,
            is_listed=False,
            notes="Well-leased Class A. Cap rate above market = potential value-add buy. 11yr hold."
        ),
        Property(
            property_id="NVA-010",
            address="3601 Wilson Blvd, Suite 100, Arlington, VA 22201",
            submarket="Arlington (Clarendon)",
            asset_class="Class B",
            total_sf=12_000,
            year_built=2002,
            last_renovation_year=2014,
            num_floors=3,
            owner_name="Wilson Corridor LLC",
            owner_type="LLC",
            owner_phone="703-555-0110",
            acquisition_date=date(2014, 2, 18),
            acquisition_price=3_200_000,
            in_place_rent_psf=30.00,
            market_rent_psf=33.00,
            market_cap_rate=6.0,
            cap_rate=6.2,
            noi=204_000,
            occupancy_pct=70.0,
            vacancy_pct=30.0,
            vacancy_12mo_ago=22.0,
            leased_sf=8_400,
            vacant_sf=3_600,
            sf_expiring_12mo=4_200,
            sf_expiring_24mo=5_880,
            lease_rollover_pct=35.0,
            last_lease_signed_date=date(2023, 6, 15),
            years_since_last_lease=2.8,
            is_listed=False,
            notes="Above-market cap rate. 35% rollover in 12mo. 12yr hold — approaching exit."
        ),
        # ── ALEXANDRIA ─────────────────────────────────────────────────────
        Property(
            property_id="NVA-011",
            address="500 N Washington St, Suite 200, Alexandria, VA 22314",
            submarket="Alexandria (Old Town)",
            asset_class="Class B",
            total_sf=8_200,
            year_built=1985,
            last_renovation_year=2005,
            num_floors=3,
            owner_name="Washington-Old Town LLC",
            owner_type="LLC",
            owner_phone="703-555-0111",
            acquisition_date=date(2008, 3, 10),
            acquisition_price=1_800_000,
            in_place_rent_psf=22.00,
            market_rent_psf=26.00,
            market_cap_rate=6.8,
            cap_rate=6.2,
            noi=98_500,
            occupancy_pct=72.0,
            vacancy_pct=28.0,
            vacancy_12mo_ago=22.0,
            leased_sf=5_904,
            vacant_sf=2_296,
            sf_expiring_12mo=2_952,
            sf_expiring_24mo=4_428,
            lease_rollover_pct=36.0,
            last_lease_signed_date=date(2022, 5, 20),
            years_since_last_lease=3.9,
            is_listed=False,
            estimated_loan_maturity_year=2027,
            notes="18yr hold. Old Town office, 41yr old building, last reno 21yr ago. Prime exit candidate."
        ),
        Property(
            property_id="NVA-012",
            address="520 N Washington St, Alexandria, VA 22314",
            submarket="Alexandria (Old Town)",
            asset_class="Class C",
            total_sf=6_800,
            year_built=1978,
            last_renovation_year=1998,
            num_floors=3,
            owner_name="Old Town Properties LLC",
            owner_type="LLC",
            owner_phone="703-555-0112",
            acquisition_date=date(2006, 11, 28),
            acquisition_price=1_400_000,
            in_place_rent_psf=21.50,
            market_rent_psf=25.50,
            market_cap_rate=6.8,
            cap_rate=7.1,
            noi=100_300,
            occupancy_pct=68.0,
            vacancy_pct=32.0,
            vacancy_12mo_ago=25.0,
            leased_sf=4_624,
            vacant_sf=2_176,
            sf_expiring_12mo=2_312,
            sf_expiring_24mo=3_698,
            lease_rollover_pct=34.0,
            last_lease_signed_date=date(2021, 1, 15),
            years_since_last_lease=5.2,
            is_listed=True,
            listing_date=date(2025, 8, 5),
            days_on_market=249,
            submarket_avg_dom=120,
            asking_price=1_550_000,
            asking_price_psf=227.94,
            notes="249 DOM (2x submarket avg). Class C. Cap rate above market = genuine upside buy."
        ),
        # ── FALLS CHURCH ───────────────────────────────────────────────────
        Property(
            property_id="NVA-013",
            address="105 Park St, Falls Church, VA 22046",
            submarket="Falls Church",
            asset_class="Class B",
            total_sf=11_200,
            year_built=1989,
            last_renovation_year=2010,
            num_floors=3,
            owner_name="Falls Church Holdings LLC",
            owner_type="LLC",
            owner_phone="703-555-0113",
            acquisition_date=date(2009, 4, 22),
            acquisition_price=2_100_000,
            in_place_rent_psf=20.00,
            market_rent_psf=23.50,
            market_cap_rate=7.0,
            cap_rate=6.8,
            noi=131_600,
            occupancy_pct=65.0,
            vacancy_pct=35.0,
            vacancy_12mo_ago=28.0,
            leased_sf=7_280,
            vacant_sf=3_920,
            sf_expiring_12mo=4_032,
            sf_expiring_24mo=5_824,
            lease_rollover_pct=36.0,
            last_lease_signed_date=date(2022, 7, 10),
            years_since_last_lease=3.7,
            is_listed=False,
            notes="17yr hold. Falls Church submarket. 37yr old building, reno 16yr ago."
        ),
        Property(
            property_id="NVA-014",
            address="400 S Maple Ave, Suite 200, Falls Church, VA 22046",
            submarket="Falls Church",
            asset_class="Class B",
            total_sf=7_500,
            year_built=1994,
            last_renovation_year=2011,
            num_floors=2,
            owner_name="Maple Office Partners",
            owner_type="LLC",
            owner_phone="703-555-0114",
            acquisition_date=date(2011, 9, 14),
            acquisition_price=1_700_000,
            in_place_rent_psf=19.50,
            market_rent_psf=23.00,
            market_cap_rate=7.0,
            cap_rate=6.0,
            noi=90_675,
            occupancy_pct=55.0,
            vacancy_pct=45.0,
            vacancy_12mo_ago=38.0,
            leased_sf=4_125,
            vacant_sf=3_375,
            sf_expiring_12mo=2_475,
            sf_expiring_24mo=4_125,
            lease_rollover_pct=33.0,
            last_lease_signed_date=date(2021, 3, 8),
            years_since_last_lease=5.1,
            is_listed=False,
            notes="15yr hold. 45% vacant and rising. Rents far below market."
        ),
        Property(
            property_id="NVA-015",
            address="2530 Columbia Pike, Arlington, VA 22204",
            submarket="Arlington (Columbia Pike)",
            asset_class="Class C",
            total_sf=9_600,
            year_built=1982,
            last_renovation_year=2004,
            num_floors=3,
            owner_name="Columbia Pike Partners",
            owner_type="LLC",
            owner_phone="703-555-0115",
            acquisition_date=date(2007, 6, 5),
            acquisition_price=1_900_000,
            in_place_rent_psf=18.00,
            market_rent_psf=22.00,
            market_cap_rate=7.2,
            cap_rate=7.5,
            noi=124_800,
            occupancy_pct=75.0,
            vacancy_pct=25.0,
            vacancy_12mo_ago=20.0,
            leased_sf=7_200,
            vacant_sf=2_400,
            sf_expiring_12mo=2_880,
            sf_expiring_24mo=4_320,
            lease_rollover_pct=30.0,
            last_lease_signed_date=date(2023, 2, 28),
            years_since_last_lease=3.1,
            is_listed=False,
            estimated_loan_maturity_year=2027,
            notes="19yr hold. Above-market cap rate. Columbia Pike redevelopment corridor."
        ),
    ]

    for prop in properties:
        if not db.query(Property).filter(Property.property_id == prop.property_id).first():
            db.add(prop)
    db.commit()
    print(f"✓ Seeded {len(properties)} properties")
    return len(properties)


def seed_companies(db):
    companies = [
        Company(
            company_id="CO-001",
            name="ClearPath Technologies",
            industry="Cybersecurity / Government IT",
            description="CMMC-certified cybersecurity firm serving DoD and federal civilian agencies. Growing rapidly on CISA contracts.",
            current_headcount=45,
            headcount_12mo_ago=32,
            open_positions=12,
            current_address="11400 Commerce Park Dr, Reston, VA 20191",
            current_submarket="Reston",
            current_sf=4_800,
            lease_expiry_date=date(2027, 1, 15),
            lease_expiry_months=9,
            primary_contact_name="David Kim",
            primary_contact_title="COO",
            primary_contact_phone="703-555-2001",
            linkedin_url="https://linkedin.com/company/clearpath-technologies",
            website="https://clearpathtechnologies.com",
        ),
        Company(
            company_id="CO-002",
            name="Apex Federal Solutions",
            industry="Government IT / Data Analytics",
            description="Federal systems integrator specializing in cloud migration and data engineering for DoD.",
            current_headcount=62,
            headcount_12mo_ago=40,
            open_positions=18,
            current_address="4075 Wilson Blvd, Arlington, VA 22203",
            current_submarket="Arlington (Ballston)",
            current_sf=5_500,
            lease_expiry_date=date(2027, 6, 30),
            lease_expiry_months=14,
            primary_contact_name="Sarah Thompson",
            primary_contact_title="CFO",
            primary_contact_phone="703-555-2002",
            linkedin_url="https://linkedin.com/company/apex-federal-solutions",
            website="https://apexfederalsolutions.com",
        ),
        Company(
            company_id="CO-003",
            name="DataCore Intelligence",
            industry="Data Analytics / AI",
            description="AI-powered analytics platform for intelligence community and commercial clients.",
            current_headcount=55,
            headcount_12mo_ago=37,
            open_positions=15,
            current_address="7600 Leesburg Pike, Suite 300, Falls Church, VA 22043",
            current_submarket="Tysons",
            current_sf=4_500,
            lease_expiry_date=date(2027, 3, 31),
            lease_expiry_months=11,
            primary_contact_name="Marcus Reyes",
            primary_contact_title="CEO",
            primary_contact_phone="703-555-2003",
            linkedin_url="https://linkedin.com/company/datacore-intelligence",
            website="https://datacoreintelligence.ai",
        ),
        Company(
            company_id="CO-004",
            name="Meridian Policy Group",
            industry="Government Affairs / Lobbying",
            description="Bipartisan policy and government affairs consulting firm serving defense and tech clients.",
            current_headcount=28,
            headcount_12mo_ago=24,
            open_positions=3,
            current_address="108 S Columbus St, Alexandria, VA 22314",
            current_submarket="Alexandria (Old Town)",
            current_sf=3_200,
            lease_expiry_date=date(2027, 12, 31),
            lease_expiry_months=20,
            primary_contact_name="Jennifer Walsh",
            primary_contact_title="Managing Director",
            primary_contact_phone="703-555-2004",
            website="https://meridianpolicygroup.com",
        ),
        Company(
            company_id="CO-005",
            name="Silverline Health Innovations",
            industry="Healthcare Technology",
            description="Digital health platform for VA health system and federal health agencies.",
            current_headcount=38,
            headcount_12mo_ago=30,
            open_positions=8,
            current_address="8300 Boone Blvd, Suite 400, Vienna, VA 22182",
            current_submarket="Tysons",
            current_sf=4_200,
            lease_expiry_date=date(2028, 7, 31),
            lease_expiry_months=31,
            primary_contact_name="Lisa Park",
            primary_contact_title="VP Operations",
            primary_contact_phone="703-555-2005",
            website="https://silverlinehealth.com",
        ),
        Company(
            company_id="CO-006",
            name="Skybridge Federal Advisors",
            industry="Management Consulting / Federal",
            description="Strategy and management consulting firm serving federal civilian and defense agencies.",
            current_headcount=34,
            headcount_12mo_ago=28,
            open_positions=7,
            current_address="3033 Wilson Blvd, Suite 700, Arlington, VA 22201",
            current_submarket="Arlington (Clarendon)",
            current_sf=3_800,
            lease_expiry_date=date(2027, 10, 31),
            lease_expiry_months=18,
            primary_contact_name="Robert Patel",
            primary_contact_title="CEO",
            primary_contact_phone="703-555-2006",
            website="https://skybridgefederal.com",
        ),
        Company(
            company_id="CO-007",
            name="NoVA Wealth Partners",
            industry="Financial Advisory / Wealth Management",
            description="RIA serving government employees, defense contractors, and federal retirees.",
            current_headcount=16,
            headcount_12mo_ago=14,
            open_positions=2,
            current_address="200 Little Falls St, Suite 400, Falls Church, VA 22046",
            current_submarket="Falls Church",
            current_sf=2_800,
            lease_expiry_date=date(2026, 10, 31),
            lease_expiry_months=6,
            primary_contact_name="Thomas Greene",
            primary_contact_title="Managing Partner",
            primary_contact_phone="703-555-2007",
            website="https://novawealthpartners.com",
        ),
        Company(
            company_id="CO-008",
            name="Patriot Logistics Solutions",
            industry="Supply Chain / Defense Logistics",
            description="Last-mile logistics and supply chain management for DoD installations.",
            current_headcount=24,
            headcount_12mo_ago=22,
            open_positions=2,
            current_address="11921 Freedom Dr, Suite 200, Reston, VA 20190",
            current_submarket="Reston",
            current_sf=2_400,
            lease_expiry_date=date(2029, 6, 30),
            lease_expiry_months=38,
            primary_contact_name="Angela Foster",
            primary_contact_title="CFO",
            primary_contact_phone="703-555-2008",
            website="https://patriotlogistics.com",
        ),
    ]

    for company in companies:
        if not db.query(Company).filter(Company.company_id == company.company_id).first():
            db.add(company)
    db.commit()
    print(f"✓ Seeded {len(companies)} companies")
    return len(companies)


def main():
    from app.config import settings

    if not settings.seed_on_init:
        print(
            "Seeding is disabled (SEED_ON_INIT=false).\n"
            "Set the environment variable SEED_ON_INIT=true to seed on a\n"
            "fresh database that has no real CoStar data yet."
        )
        sys.exit(0)

    print("Deal Radar OS — Initializing database and seeding Northern Virginia data")
    print("=" * 65)

    init_db()
    db = SessionLocal()

    try:
        prop_count    = seed_properties(db)
        company_count = seed_companies(db)

        print("\nRunning full signal pipeline...")
        result = run_full_pipeline(db)

        print(f"\n✓ Pipeline complete:")
        print(f"  Properties:       {result['properties_refreshed']}")
        print(f"  Companies:        {result['companies_refreshed']}")
        print(f"  New opportunities: {result['new_opportunities']}")
        print(f"  Runtime:          {result['elapsed_seconds']}s")

        # Print summary of top opportunities
        from app.models.opportunity import Opportunity
        top = db.query(Opportunity).order_by(Opportunity.score.desc()).limit(5).all()
        print(f"\n{'─'*65}")
        print("TOP 5 OPPORTUNITIES:")
        for i, opp in enumerate(top, 1):
            prop_addr = opp.property.address if opp.property else "N/A"
            company_name = opp.company.name if opp.company else "—"
            print(f"  {i}. [{opp.priority}] {opp.deal_type} | Score: {opp.score:.0f}")
            print(f"     Property: {prop_addr}")
            if company_name != "—":
                print(f"     Company:  {company_name}")
            print(f"     Thesis:   {opp.thesis[:120]}...")
            print()

    finally:
        db.close()


if __name__ == "__main__":
    main()
