export const SUBMARKETS = [
  'Arlington (Clarendon)',
  'Arlington (Rosslyn)',
  'Arlington (Ballston)',
  'Arlington (Columbia Pike)',
  'Alexandria (Old Town)',
  'Tysons',
  'Reston',
  'Falls Church',
  'McLean',
  'Vienna',
  'Fairfax City',
  'Annandale',
  'Crystal City',
  'Merrifield',
  'Springfield',
  'Centreville',
]
